language: go

go:
  - 1.11.x

env:
  - CGO_ENABLED=1

before_install:
  - go get -u golang.org/x/lint/golint
  - go get -u github.com/mitchellh/gox
  - go get -u github.com/golang/dep/cmd/dep

secure: "ID8DI+DqeSTb80YK01sqIzN8WfiDrwtZLWaCSNzIiLhxzciUlfmr3GxfQFhZId6ACOGMVxJfmz01g2xWxscFuGu2QKgB6ky8I1PXzHnBAXmYtgjvCaw8Ll05mCzQOD8EZErr8pvSngpZb7Pio/AmvKytI24Y0Co8GvLjViQt5FYCBZ9Oglx5ozZodLsy9aUws6cp0v1ZL1kD4lpUnBjr47ejWMZ0l22AqzNLTa7K2WxYLWdwHGh1SncdH/3FVPycR6/l3ZzZ6SBwMl3TIZykm3FIpLUOsQG4hg7rR1ktEEPnjHj+UOAW0GRcUbsPbJUSfrqnbkRcqjSXhB7kHnKI+q5RQrO8NHc4EWTAd48O3MmHUQJWxTkaKiT3U3UxHm0HfApAUPjYtTgfMk0AERjWpbE2dGfoFFMP6j13A2z/LUjJgtpJiIHgpX0rWXRrOTz1jYTaCcxtetdO35aA5gyVNKzmNZ7YKEH1LGS64a+3K4K757ja6yIgq8i4DZXFqOaTPRq0qF8LVKYmUrgPepmWetATpFNxhEm4LsSDiRDj3tWQhxdkDcMldER0F95McKPmUhGMT1sBgK+v7bwyvaSEg4AXroz0It7KyRmUkJUxNsFpiEk+2xvFpvO0AGr/3P4wLXEMZ0dkGzZ/k4bLwH4EPuA1lX2sVzDCzm6CZLrQuAI="

script:
  - golint ./...
  - dep init
  - go test -cpu=1,2 -v -tags integration ./...
  - gox -ldflags="-X main.VERSION=1" -osarch="darwin/amd64 linux/amd64 windows/amd64" -output="compiled/{{.Dir}}_{{.OS}}_{{.Arch}}"
  - |
    for binary in kubeauth_darwin_amd64 kubeauth_linux_amd64 kubeauth_windows_amd64.exe; do
      # upload compiled/$binary to nexus
        if [[ $binary =~ darwin ]]; then
          platform="osx"
          exec="kubeauth"
        elif [[ $binary =~ linux ]]; then
          platform="linux"
          exec="kubeauth"
        elif [[ $binary =~ windows ]]; then
          platform="windows"
          exec="kubeauth.exe"
        else
          platform="unknown"
          exec="kubeauth"
        fi
        curl -v -u "$CRED" --upload-file compiled/$binary http://nexus.wt0f.com:8081/repository/kubeauth/${platform}/${exec}
    done

