# Habitus build file
---
build:
  version: 2016-03-14
  steps:
    dex-build:
      name: dex
      dockerfile: Dockerfile.dex

    auth-crosscompile:
      name: kubeauth
      dockerfile: Dockerfile.kubeauth
      artifacts:
        - /go/src/github.com/hickey/kubeauth/compiled:.

